### ISSUE TITLE
När ska vi ha nästa hackday?

### ISSUE THREAD

**Issue by mattische** [dite-bth/hackday#2]
När? Vad? Hur?

**Comment by kevintatou** [comment]
Tycker i april. Tycker att vi även ska ha hackday mer än en dag, kanske över en helg till och med. Och att det ska vara nån form av kodning involverat i form av digitalt helst. Vad sägerru?

**Comment by mattische** [comment]
Låter bra. Det finns även en idé om att träffas typ varannan fredag och kötta loss.
Alla har dessutom inte färdigställt arkadmaskinerna.
Vi kanske skulle ta ett möte?

**Comment by kevintatou** [comment]
Det hade varit kul det med! Att göra en rutin av det! När kan du ha möte? Är i skolan i princip hela nästa vecka och är i skolan imorgon.

**Comment by mattische** [comment]
Måndag kl. 15:00?
Vi kan väl bjuda in alla som vill vara med?

**Comment by kevintatou** [comment]
Låter bra! Ja det tycker jag :D Inte bara webb!

**Comment by mattische** [comment]
sdf
